name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4 ]

    name: Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Install PHP dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
            mkdir -p storage/framework/views
            composer install --no-interaction --no-progress --ansi --optimize-autoloader

      - name: Setup test env configuration
        run: |
          touch database/database.sqlite
          cp .env.testing.example .env

      - name: Create Laravel storage folders
        run: |
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/logs
          mkdir -p bootstrap/cache

      - name: Set permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Generate app key
        run: |
          php artisan key:generate

      - name: Run tests
        run: composer test
